flyway.url=jdbc:postgresql://localhost:5432/dashboarddb
flyway.user=postgres
flyway.password=postgres
flyway.schemas=flyway
flyway.createSchemas=true
flyway.locations=filesystem:sql
flyway.cleanDisabled=true